version: '3.8'

services:
  odooweb:
    image: ghcr.io/jsolisba/odoo:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - dbodoo
    ports:
      - '8070:8069'
      - '7788:7788'
    secrets:
      - postgresql_password
    networks:
      - odoo_backend
      - odoo_frontend
    volumes:
      - odoo-addons:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo
      - odoo-filestore:/var/lib/odoo/.local/share/Odoo/filestore
      - ../../config/prod.conf:/etc/odoo/odoo.conf:ro

  dbodoo:
    image: custom-postgres:15.10
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgresql_password
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
#      PGDATA: /var/lib/postgresql/data/pgdata
      PGDATA: /var/lib/postgresql/data
    volumes:
#     - odoo-db-data:/var/lib/postgresql/data/pgdata
      - odoo-db-data:/var/lib/postgresql/data
    secrets:
      - postgresql_password
    networks:
      - odoo_backend

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  odoo-web-data:
    external: true
  odoo-db-data:
    external: true
  odoo-addons:
    external: true
  odoo-filestore:
    external: true
secrets:
  postgresql_password:
    external: true

networks:
  odoo_frontend:
    driver: overlay
  odoo_backend:
    driver: overlay
