[options]

proxy_mode = True

addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

db_host = dbodoo
db_port = 5432
db_user = odoo

dbfilter = ^%d$

admin_passwd = $pbkdf2-sha512$600000$VEqptZbyPkeotXbOWSulNA$EtylwBhyNfE/SWgeNd9y3j.cPH8hWRx.libo/k.RNnNnHk6OVV0L5xqppsIayuJwUnNYvcLYGxcdeIZ21klhHg

list_db = True

workers = 0

log_level = debug

dev = reload,qweb,xml

limit_time_cpu = 600
limit_time_real = 1200

limit_memory_soft = 2147483648
limit_memory_hard = 2684354560